add_newline = true

[line_break]
disabled = true

[username]
# style_root = "white bold"
format = "[ $user](yellow bold)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@](bold red)[ï£¿$hostname](blue) "
# format = "[ïŒš ](yellow bold)"
trim_at = "."
disabled = false

[conda]
ignore_base = false
format = "[$symbol$environment ](dimmed green)"

[python]
format = "[$symbol$version ](bold )"
symbol =  "ğŸ"
# symbol =  "î˜† "

[ruby]
disabled = true

right_format = "$all"
