add_newline = true

[line_break]
disabled = true

[username]
# style_root = "white bold"
format = "[ $user](yellow bold)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[@](bold red)[ï£¿$hostname](blue) "
# format = "[ïŒš ](yellow bold)"
trim_at = "."
disabled = false

[conda]
ignore_base = false
format = "[$symbol$environment ](dimmed green)"

[python]
format = "[$symbol$version ](bold )"
symbol =  "ğŸ"
# symbol =  "î˜† "

[ruby]
disabled = true

[git_status]
conflicted = "âš”ï¸ "
ahead = "â‡¡"
behind = "[â‡£${count} ](bold dimmed blue)"
diverged = "â‡•${ahead_count}â‡£${behind_count} "
untracked = "[?${count} ](bold red)"
modified ="[!${count} ](bold yellow)"
staged = "[+${count} ](bold green)"
renamed = "Â» Ã—${count} "
deleted = "[âœ˜ Ã—${count} ](bold red)"
style = "bold purple"
format = '([\[$all_status$ahead_behind\]]($style) )'
